### ISSUE TITLE
yidas/yii2-bower-asset This won't be necessary 

### ISSUE THREAD

**Issue by zhanchmini** [charlesportwoodii/yii2-psr7-bridge#17]
```
    'aliases' => [
        '@bower' => '@vendor/yidas/yii2-bower-asset/bower',
    ]
```

/dist/js/bootstrap.bundle.js not fond

**Comment by charlesportwoodii** [comment]
The wiki outlines the most recent configuration: https://github.com/charlesportwoodii/yii2-psr7-bridge/wiki/RoadRunner-2.9--%7C-Yii2-Configuration-with-yii-app-basic as of April 2022.

**Comment by zhanchmini** [comment]
> ```
>     'aliases' => [
>         '@bower' => '@vendor/yidas/yii2-bower-asset/bower',
>     ]
> ```
> 
> /dist/js/bootstrap.bundle.js not fond

```
        "php": ">=7.4.0",
        "yiisoft/yii2": "~2.0.45",
        "yiisoft/yii2-bootstrap5": "~2.0.2",
        "yiisoft/yii2-symfonymailer": "~2.0.3",
```
They've upgraded.  There's no upgrade on your end

**Comment by charlesportwoodii** [comment]
The dependencies listed in the wiki are the minimum tested. You are not restricted to the minimums if newer ones work.
